name: OWASP ZAP Security Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions for ZAP
        run: |
          sudo chmod -R 777 ${{ github.workspace }}

      - name: Run OWASP ZAP baseline scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "https://testphp.vulnweb.com"
          cmd_options: "-m 1 --autooff"  
        continue-on-error: true

      - name: Check for high or critical alerts (não interrompe o pipeline)
        run: |
          echo "Verificando vulnerabilidades críticas no relatório..."
          if grep -q -E "High|Critical" report_html.html; then
            echo "⚠️ Falhas críticas detectadas! O relatório será salvo mesmo assim."
          else
            echo "✅ Nenhuma vulnerabilidade crítica encontrada."
          fi


      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
